airball/urls.py
from django.conf.urls import url, include

from airball import views
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import logout

urlpatterns = [
	url(r'^admin/', admin.site.urls),
  	url(r'^$', views.index, name='index'),
	url(r'^formulario/', views.form_user, name="form-user"),
	url(r'^jogadores/', views.players, name="players"),
	url(r'^jogadorestatistica/', views.player_statistic, name="player_statistic"),
	url(r'^jogadorestatisticacomparacao/', views.player_statistic_comparison, name="player_statistic_comparison"),
	url(r'^times/', views.teams, name="teams"),
	url(r'^timeestatistica/', views.team_statistic, name="team_statistic"),
	url(r'^timeestatisticacomparacao/', views.team_statistic_comparison, name="team_statistic_comparison"),
	url(r'^login/', views.form_login, name="login"),
	url(r'^agenda/', views.schedule, name="schedule"),
	url(r'^jogador', views.player, name="player"),
	url(r'^time', views.team, name="team"),
	url(r'^quiz/', views.questions, name="quiz"),
	url(r'^noticias/', views.news, name="noticias"),
	url(r'^logout/', views.logout_view, name='logout'),
	url(r'^cadastro/',include('app.urls',namespace='cadastre')),
	
]

app/urls.py
from django.conf.urls import url, include
from app import views as v

urlpatterns = [

	url(r'^time/lista',v.TeamListView.as_view(),name='list_teams'),
    url(r'^time/atualizar/(?P<pk>\d+)',v.TeamUpdateView.as_view(success_url='../lista'),name='update_team'),
    url(r'^jogador/lista',v.PlayerListView.as_view(),name='list_players'),
    url(r'^jogador/atualizar/(?P<pk>\d+)',v.PlayerUpdateView.as_view(success_url='../lista'),name='update_player'),
    url(r'^quiz/lista',v.QuestionListView.as_view(),name='list_questions'),
    url(r'^quiz/atualizar/(?P<pk>\d+)',v.QuestionUpdateView.as_view(success_url='../lista'),name='update_question'),
    url(r'^quiz/remover/(?P<pk>\d+)',v.DeleteQuestion,name='delete_question'),
    url(r'^quiz/criar/',v.QuestionCreateView.as_view(success_url='../lista'),name='create_question'),
]

app/models.py
from django.db import models
from decimal import Decimal

# Create your models here.
class Conference(models.Model):
    
    id = models.AutoField(primary_key=True)
    id_nba = models.CharField(max_length=80)
    name = models.CharField(max_length=5, unique=True)
    name_br = models.CharField(max_length=10)

    def __str__(self):
        return ("%s conference" % self.name)

    def natural_key(self):
        return (self.id,self.name,self.name_br)

class Division(models.Model):
    
    id = models.AutoField(primary_key=True)
    id_nba = models.CharField(max_length=80)
    conference = models.ForeignKey(Conference)
    name = models.CharField(max_length=10, unique=True)
    name_br = models.CharField(max_length=15)
    
    def __str__(self):
        return ("%s division" % self.name)

    def natural_key(self):
        return (self.id,self.name,self.name_br) + self.conference.natural_key()

class Team(models.Model):
    
    id = models.AutoField(primary_key=True)
    id_nba = models.CharField(max_length=80, unique=True)   
    division = models.ForeignKey(Division, null=True)
    name = models.CharField(max_length=30, unique=True)
    fundation_date = models.IntegerField()
    owner = models.CharField(max_length=60)
    general_manager = models.CharField(max_length=60)
    city = models.CharField(max_length=60)
    arena = models.CharField(max_length=60)
    coach = models.CharField(max_length=60)
    description = models.TextField()

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.id,self.name,) + self.division.natural_key()

class Player(models.Model):

    id = models.AutoField(primary_key=True)
    id_nba = models.CharField(max_length=80, unique=True)
    team = models.ForeignKey(Team, null=True)
    name = models.CharField(max_length=50)
    birth_date = models.DateField()
    height = models.CharField(max_length=5)
    weight = models.CharField(max_length=5)
    college = models.CharField(max_length=60 , null=True, default="nenhuma")
    position = models.CharField(max_length=15)
    number = models.IntegerField(null=True, default=0, blank=True)
    experience = models.IntegerField()
    draft = models.CharField(max_length=15)
    description = models.TextField()

    def __str__(self):
        return self.name
    
    def natural_key(self):
        return (self.id,self.name,self.number) + self.team.natural_key()
    
class Season(models.Model):
        
    id = models.AutoField(primary_key=True)
    # champion = models.ForeignKey(Team)
    year = models.CharField(max_length=7)

    def __str__(self):
        return self.year

class PlayerStatistic(models.Model):

    id = models.AutoField(primary_key=True)        
    season = models.ForeignKey(Season)
    player = models.ForeignKey(Player)
    playoff = models.BooleanField(null=False)

    ppg = models.DecimalField(max_digits=5, decimal_places=2)
    rpg = models.DecimalField(max_digits=5, decimal_places=2)
    apg = models.DecimalField(max_digits=5, decimal_places=2)
    bpg = models.DecimalField(max_digits=5, decimal_places=2)
    spg = models.DecimalField(max_digits=5, decimal_places=2)
    tpg = models.DecimalField(max_digits=5, decimal_places=2)
    mpg = models.DecimalField(max_digits=5, decimal_places=2)
    
    ttp = models.DecimalField(max_digits=5, decimal_places=3)
    fgp = models.DecimalField(max_digits=5, decimal_places=3)
    ftp = models.DecimalField(max_digits=5, decimal_places=3)

    ftm = models.IntegerField()
    fgm = models.IntegerField()
    ttm = models.IntegerField()

    def __str__(self):
        return self.name
    
    def natural_key(self):
        return (self.id,) + self.player.natural_key()
    
    class Meta:         
         ordering=['season']      
         unique_together = ('season', 'player', 'playoff')

class TeamStatistic(models.Model):
    
    id = models.AutoField(primary_key=True)
    season = models.ForeignKey(Season)
    team = models.ForeignKey(Team)
    playoff = models.BooleanField(null=False)

    ppg = models.DecimalField(max_digits=5, decimal_places=2)
    rpg = models.DecimalField(max_digits=5, decimal_places=2)
    apg = models.DecimalField(max_digits=5, decimal_places=2)
    bpg = models.DecimalField(max_digits=5, decimal_places=2)
    spg = models.DecimalField(max_digits=5, decimal_places=2)
    tpg = models.DecimalField(max_digits=5, decimal_places=2)
    
    ttp = models.DecimalField(max_digits=5, decimal_places=2)
    fgp = models.DecimalField(max_digits=5, decimal_places=2)
    ftp = models.DecimalField(max_digits=5, decimal_places=2)

    wins = models.IntegerField()
    loses = models.IntegerField()
    
    oppPts = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.name
    
    def natural_key(self):
        return (self.id,) + self.team.natural_key()

    class Meta:         
         ordering=['season']      
         unique_together = ('season', 'team', 'playoff')

class News(models.Model): 

    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=250)
    url = models.URLField(unique=True)
    url_image = models.URLField(unique=True)
    date = models.DateField()
    description = models.CharField(max_length=1000)
    
class Schedule(models.Model): 

    id = models.AutoField(primary_key=True)
    home_team = models.ForeignKey(Team, related_name="home_team")
    visitor_team = models.ForeignKey(Team, related_name="visitor_team")

    scheduled_date = models.DateTimeField()
    home_points = models.IntegerField()
    visitor_points = models.IntegerField()

class Question(models.Model):

    id = models.AutoField(primary_key=True)
    question = models.TextField()
    answer_1 = models.CharField(max_length=250)
    answer_2 = models.CharField(max_length=250)
    answer_3 = models.CharField(max_length=250)
    answer_4 = models.CharField(max_length=250)
    answer_5 = models.CharField(max_length=250)
    correct_answer = models.IntegerField()

airball/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,

    )
from django.shortcuts import render, redirect

from app import forms
from app.models import Player, Team, Division, Conference, Season, PlayerStatistic, TeamStatistic, Schedule, Question
import datetime
from random import shuffle


from django.core import serializers

from app.util import get_new, get_players, get_teams, get_player_stats, get_team_stats, get_file
# Create your views here.

def index(request):

    user = request.user
    news = get_new('http://www.nba.com/rss/nba_rss.xml')
    date_dict={"news_list": news[0:6], "user": user}

    return render(request, 'airball/index.html',  context = date_dict)

def news(request):
    
    news = get_new('http://www.nba.com/rss/nba_rss.xml')
    date_dict={"news_list": news}

    return render(request, 'airball/news.html',  context = date_dict)

def form_user(request):
    print(request.user.is_authenticated())
    next = request.GET.get('next')
    title = "Register"
    form = forms.FormUser(request.POST)
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password')
        user.set_password(password)
        user.save()
        new_user = authenticate(username=user.username, password=password)
        login(request, new_user)
        if next:
            return redirect(next)
        return redirect("/")

    context = {
        "form": form,
        "title": title
    }
    return render(request, "airball/form-user.html", context)

def players(request):
    return render(request, 'airball/grid-player.html',  context = get_players())

def teams(request):
    return render(request, 'airball/grid-team.html',  context = get_teams())

def player(request):
    date_dict={}
    if (request.method == 'GET'):
        param = request.GET['jogador']
        
        player = Player.objects.get(id=param)
        
        statistics = []
        try:
            statistics.append(PlayerStatistic.objects.get(player=player,playoff=False))
            statistics.append(PlayerStatistic.objects.get(player=player,playoff=True))
        except:
            pass
            
        date_dict={"player": player, "statistics": statistics}

    return render(request, 'airball/player.html',  context = date_dict)

def team(request):
    date_dict={}
    if (request.method == 'GET'):
        param = request.GET['time']
        
        team = Team.objects.get(id=param)
        
        statistics = []
        try:
            statistics.append(TeamStatistic.objects.get(team=team,playoff=False))
            statistics.append(TeamStatistic.objects.get(team=team,playoff=True))
        except:
            pass

        date_dict={"team": team, "statistics": statistics}

    return render(request, 'airball/team.html',  context = date_dict)

def questions(request):
    questions = Question.objects.all().order_by('?')
    # shuffle(questions)

    date_dict={"questions": serializers.serialize("json", questions)}
    
    return render(request, 'airball/questions.html',  context = date_dict)

def player_statistic(request):
    order_by = request.GET.get('order_by', 'ppg')
    palyerStats = PlayerStatistic.objects.all().order_by('-'+order_by)
    date_dict = {"statistics": palyerStats}
    return render(request, 'airball/grid-player-statistic.html',  context = date_dict)

def form_login(request):
    print(request.user.is_authenticated())
    next = request.GET.get('next')

    form = forms.FormLogin(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        if next:
            return redirect(next)
        return redirect("http://localhost:8000/")

    return render(request, 'airball/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect("/")

def team_statistic(request):
    order_by = request.GET.get('order_by', 'wins')
    teamStats = TeamStatistic.objects.all().order_by('-'+order_by)
    date_dict = {"statistics": teamStats}
    return render(request, 'airball/grid-team-statistic.html',  context = date_dict)

def player_statistic_comparison(request):

    player_1 = request.POST.get('player_1', 'LeBron James')
    player_2 = request.POST.get('player_2', 'Stephen Curry')
    
    player1 = Player.objects.get(name=player_1)
    player2 = Player.objects.get(name=player_2)


    playerStats1 = PlayerStatistic.objects.get(player=player1)
    playerStats2 = PlayerStatistic.objects.get(player=player2)

    date_dict={"statistics_players": serializers.serialize("json", [playerStats1, playerStats2], use_natural_foreign_keys=True), "players": get_players()}
       
    # date_dict={"statistics_players": serializers.serialize("json", [statistic1, statistic2], use_natural_foreign_keys=True), "players": get_players()}

    return render(request, 'airball/grid-player-statistic-comparison.html', context = date_dict)

def team_statistic_comparison(request):

    team_1 = request.POST.get('team_1', 'Warriors')
    team_2 = request.POST.get('team_2', 'Cavaliers')
    
    team1 = Team.objects.get(name=team_1)
    team2 = Team.objects.get(name=team_2)


    teamStats1 = TeamStatistic.objects.get(team=team1)
    teamStats2 = TeamStatistic.objects.get(team=team2)


    date_dict={"statistics_teams": serializers.serialize("json", [teamStats1, teamStats2], use_natural_foreign_keys=True),  "teams": get_teams()}

    return render(request, 'airball/grid-team-statistic-comparison.html',  context=date_dict)

def schedule(request):
   
    date_dict = {"schedules": get_file('static/assets/games.csv')}

    return render(request, 'airball/grid-schedule.html',  context=date_dict)

templates/airball/form-user.html
{% extends 'airball/template-main.html' %} {% load staticfiles %} {% block header %}
<link rel="stylesheet" href="{% static 'css/form-user.css' %}">
<title>Cadastro de Usuário</title>
{% endblock %} {% block container %}
<h2>Cadastro de Usuário</h2>
<form class="form-horizontal" action="" method="POST"> {% csrf_token %} {% for field in form %}
    <div class="container">
        <div class="row">
            <div class="col col-left">
                <label>{{ field.label }}</label>
            </div>
            <div class="col col-9">
                {{ field }}
            </div>
        </div>
    </div>
    {% endfor %}

    <br>
    <div class="form-group">
        <div class="row">
            <div class="col">
                <!-- <p>Texto Aleatorio</p> -->
            </div>
            <div class="col-9">
                <button type="submit" class="btn btn-success btn-submit">Enviar</button>
            </div>
        </div>
    </div>
    </div>
</form>

{% endblock %}

templates/airball/grid-player-statistic-comparison.html
{% extends 'airball/template-main.html' %}
{% load staticfiles %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/player.css' %}">
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>

    <title>Comparação estatística entre jogadores</title>
{% endblock %} 
    
{% block container %}
<form action="player_statistic_comparison" method="post"> {% csrf_token %}
    <div class="row">
        <div class="col-sm-3" style="text-align: right;">
            <label class="col-sm-2 col-form-label" style="margin-right: 70px;">Jogadores</label>
        </div>
        <div class="col-sm-3">
            <select id="select1" class="form-control collectes-ville text-center" name="player_1">
                {% for player in players.players %}
                <option value="{{ player }}">{{ player.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-sm-3">
            <select id="select2" class="form-control collectes-ville text-center" name="player_2">
                {% for player2 in players.players %}
                <option value="{{ player2 }}">{{ player2.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-sm-3">
            <input   type="submit" class="btn btn-default btn-submit" value="Calcular">
        </div>
    </div>
</form>
    
    <br>
    
    <div id="comparison">
        <div class="row">
            <div class="col-md-6">
                <a id="player1-page" href=""><h3 id="player1-name" class="right-alignment"></h3><a>
                <a id="player1-team-page" href=""><h6 id="player1-team" class="right-alignment"></h6><a>
            </div>
            <div class="col-md-6 left-alignment">
                <a id="player2-page" href=""><h3 id="player2-name" class="left-alignment"></h3><a>
                <a id="player2-team-page" href=""><h6 id="player2-team" class="left-alignment"></h6><a>
            </div>
        </div>
        
        <div id="container" style="width: 100%; margin: 0 auto"></div>
    </div>

    <script type="text/javascript">
        statistics = {{ statistics_players|safe }};
    </script>
    
    <script src="{% static 'js/player-comparison-chart.js' %}"></script>
{% endblock %}

templates/airball/grid-player-statistic.html
{% extends 'airball/template-main.html' %} 
{% load staticfiles %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/player.css' %}">
    <title>Estatísticas de jogadores</title>
{% endblock %} 
    
{% block container %}      
    <h2>Estatísticas de jogadores</h2>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Posição</th>
                <th>Time</th>
                <th>Número</th>
                <!-- <th><a class="tooltip">Altura<span class="tooltiptext">Altura</span></a></th>
                <th><a class="tooltip">Peso<span class="tooltiptext">Peso</span></a></th> -->
                <th>Temporada</th>
                <!-- <th>Playoff</th> -->
                <th><a class="tooltip" href="?order_by=ppg">PPG<span class="tooltiptext">Pontos por Jogo</span></a></th>
                <th><a class="tooltip" href="?order_by=rpg">RPG<span class="tooltiptext">Rebotes por Jogo</span></a></th>
                <th><a class="tooltip" href="?order_by=apg">APG<span class="tooltiptext">Assistências por Jogo</span></a></th>
                <th><a class="tooltip"href="?order_by=bpg">BPG<span class="tooltiptext">Tocos por Jogo</span></a></th>
                <th><a class="tooltip"href="?order_by=spg">SPG<span class="tooltiptext">Roubadas por Jogo</span></a></th>
                <th><a class="tooltip"href="?order_by=tpg">TPG<span class="tooltiptext">Turn Overs por Jogo</span></a></th>
                <th><a class="tooltip"href="?order_by=mpg">MPG<span class="tooltiptext">Minutos por Jogo</span></a></th>
                <th><a class="tooltip"href="?order_by=ftp">FTP<span class="tooltiptext">Lances Livres Percentual</span></a></th>
                <th><a class="tooltip"href="?order_by=fgp">FGP<span class="tooltiptext">Field Goals Percentual</span></a></th>
                <th><a class="tooltip"href="?order_by=ttp">TTP<span class="tooltiptext">3pts Percentual</span></a></th>
                <th><a class="tooltip"href="?order_by=ftm">FTM<span class="tooltiptext">Lances Livres convertidos</span></a></th>
                <th><a class="tooltip"href="?order_by=fgm">FGM<span class="tooltiptext">Field Goals convertidos</span></a></th>
                <th><a class="tooltip"href="?order_by=ttm">TTM<span class="tooltiptext">3pts convertidos</span></a></th>
            </tr>
        </thead>
        <tbody>
            {% for statistic in statistics %}
            <tr>
                <td><a href="{% url 'player' %}?jogador={{player.id_nba}}">{{statistic.player.name}}</a></td>
                <td>{{statistic.player.position}}</td>
                <td>{{statistic.player.team.name}}</td>
                <td>{{statistic.player.number}}</td>
                <!-- <td>{{statistic.player.height}}</td>
                <td>{{statistic.player.weight}}</td> -->
                <td>{{statistic.season.year}}</td>
                
                <!-- {% if statistic.playoff %}
                    <td>Sim</td>
                {% else %}
                    <td>Não</td>
                {% endif %} -->

                <td>{{statistic.ppg}}</td>
                <td>{{statistic.rpg}}</td>
                <td>{{statistic.apg}}</td>
                <td>{{statistic.bpg}}</td>
                <td>{{statistic.spg}}</td>
                <td>{{statistic.tpg}}</td>
                <td>{{statistic.mpg}}</td>
                <td>{{statistic.ftp}}</td>
                <td>{{statistic.fgp}}</td>
                <td>{{statistic.ttp}}</td>
                <td>{{statistic.ftm}}</td>
                <td>{{statistic.fgm}}</td>
                <td>{{statistic.ttm}}</td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/airball/grid-player.html
{% extends 'airball/template-main.html' %} 
{% load staticfiles %} 

{% block header %}
<link rel="stylesheet" href="{% static 'css/player.css' %}">
<title>Jogadores</title>
{% endblock %} 

{% block container %}
    <h2>Jogadores</h2>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Posição</th>
                <th>Time</th>
                <th>Número</th>
                <th>Altura</th>
                <th>Peso</th>
                <th>Data Nascimento</th>
                <th>Universidade</th>
                <th>Draft</th>
                <th>Experiência (anos)</th>
            </tr>
        </thead>
        <tbody>
            {% for player in players %}
            <tr>
                <td><a href="{% url 'player' %}?jogador={{player.id}}">{{player.name}}</a></td>
                <td>{{player.position}}</td>
                <td>{{player.team.name}}</td>
                <td>{{player.number}}</td>
                <td>{{player.height}}</td>
                <td>{{player.weight}}</td>
                <td>{{player.birth_date}}</td>
                <td>{{player.college}}</td>
                <td>{{player.draft}}</td>
                <td>{{player.experience}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/airball/grid-team-statistic.html
{% extends 'airball/template-main.html' %} 
{% load staticfiles %} 

{% block header %}
<link rel="stylesheet" href="{% static 'css/team.css' %}">
<title>Estatísticas de Times</title>
{% endblock %} 

{% block container %}
<h2>Estatísticas de Times</h2>

<table class="table table-hover">
    <thead>
        <tr>
            <th><a href="?order_by=team">Nome</a></th>
            <th>Temporada</th>
            <th>Playoff</th>
            <th><a class="tooltip"  href="?order_by=wins">Vitórias</a></th>
            <th><a class="tooltip" href="?order_by=loses">Derrotas</a></th>
            <th><a class="tooltip" href="?order_by=ppg">PPG<span class="tooltiptext">Pontos por Jogo</span></a></th>
            <th><a class="tooltip" href="?order_by=rpg">RPG<span class="tooltiptext">Rebotes por Jogo</span></a></th>
            <th><a class="tooltip" href="?order_by=apg">APG<span class="tooltiptext">Assistências por Jogo</span></a></th>
            <th><a class="tooltip"href="?order_by=bpg">BPG<span class="tooltiptext">Tocos por Jogo</span></a></th>
            <th><a class="tooltip"href="?order_by=spg">SPG<span class="tooltiptext">Roubadas por Jogo</span></a></th>
            <th><a class="tooltip"href="?order_by=tpg">TPG<span class="tooltiptext">Turn Overs por Jogo</span></a></th>
            <th><a class="tooltip"href="?order_by=ftp">FTP<span class="tooltiptext">Lances Livres Percentual</span></a></th>
            <th><a class="tooltip"href="?order_by=fgp">FGP<span class="tooltiptext">Field Goals Percentual</span></a></th>
            <th><a class="tooltip"href="?order_by=ttp">TTP<span class="tooltiptext">3pts Percentual</span></a></th>
            <!-- <th>Op. PPG</th> -->
        </tr>
    </thead>
    <tbody>
        {% for statistic in statistics %}
        <tr>
            <td><a href="{% url 'team' %}?time={{team.id_nba}}">{{statistic.team.name}}</a></td>
            <td>{{statistic.season.year}}</td>
            
            {% if statistic.playoff %}
                <td>Sim</td>
            {% else %}
                <td>Não</td>
            {% endif %}

            <td>{{statistic.wins}}</td>
            <td>{{statistic.loses}}</td>
            <td>{{statistic.ppg}}</td>
            <td>{{statistic.rpg}}</td>
            <td>{{statistic.apg}}</td>
            <td>{{statistic.bpg}}</td>
            <td>{{statistic.spg}}</td>
            <td>{{statistic.tpg}}</td>
            <td>{{statistic.ftp}}</td>
            <td>{{statistic.fgp}}</td>
            <td>{{statistic.ttp}}</td>
            <!-- <td>{{statistic.oppPts}}</td> -->

        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/airball/template-main.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge"> {% block header %}
  <title>Airball</title>
  {% endblock %}

  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">

</head>

<body>

  <nav class="navbar navbar-toggleable-md fixed-top navbar-inverse bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
      aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'index' %}">Airball</a>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
  
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'schedule' %}">Agenda
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'quiz' %}">Quiz</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="dropdownTime" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Time</a>
          <div class="dropdown-menu" aria-labelledby="dropdownTime">
            <a class="dropdown-item" href="{% url 'teams' %}">Times</a>
            <a class="dropdown-item" href="{% url 'team_statistic' %}">Estatística</a>
            <a class="dropdown-item" href="{% url 'team_statistic_comparison' %}">Comparação</a>
          </div>
        </li>
     
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="dropdownPlayer" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Jogador</a>
            <div class="dropdown-menu" aria-labelledby="dropdownPlayer">
              <a class="dropdown-item" href="{% url 'players' %}">Times</a>
              <a class="dropdown-item" href="{% url 'player_statistic' %}">Estatística</a>
              <a class="dropdown-item" href="{% url 'player_statistic_comparison' %}">Comparação</a>
            </div>
          </li>
  
      </ul>
      {% if user.is_active %}
      <ul class="nav navbar-nav navbar-right">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="dropdownPlayer" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{user.username}}</a>
          <div class="dropdown-menu  dropdown-menu-right text-right" aria-labelledby="dropdownPlayer">
              <a class="dropdown-item" href="{% url 'cadastre:list_teams' %}">Cadastro de times</a>
              <a class="dropdown-item" href="{% url 'cadastre:list_players' %}">Cadastro de Jogadores</a>
              <a class="dropdown-item" href="{% url 'cadastre:list_questions' %}">Cadastro de Questões</a>
            <a class="dropdown-item" href="{% url 'logout' %}">Sair</a>
          </div>
        </li>
      </ul>
      {% else %}
      <a class="btn btn-outline-success my-2 my-sm-0" href="../login">Login</a>
      {% endif %}
    </div>
  </nav>

  <div class="container my-container">
    {% block container %} {% endblock %}
  </div>
</body>

{# Plugins#}


<!-- Latest compiled and minified JavaScript -->
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n"
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
  crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

</html>