airball/urls.py
from django.conf.urls import url, include

from airball import views
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import logout

urlpatterns = [
	url(r'^admin/', admin.site.urls),
  	url(r'^$', views.index, name='index'),
	url(r'^formulario/', views.form_user, name="form-user"),
	url(r'^jogadores/', views.players, name="players"),
	url(r'^jogadorestatistica/', views.player_statistic, name="player_statistic"),
	url(r'^jogadorestatisticacomparacao/', views.player_statistic_comparison, name="player_statistic_comparison"),
	url(r'^times/', views.teams, name="teams"),
	url(r'^timeestatistica/', views.team_statistic, name="team_statistic"),
	url(r'^timeestatisticacomparacao/', views.team_statistic_comparison, name="team_statistic_comparison"),
	url(r'^login/', views.form_login, name="login"),
	url(r'^agenda/', views.schedule, name="schedule"),
	url(r'^jogador', views.player, name="player"),
	url(r'^time', views.team, name="team"),
	url(r'^quiz/', views.questions, name="quiz"),
	url(r'^noticias/', views.news, name="noticias"),
	url(r'^logout/', views.logout_view, name='logout'),
	url(r'^cadastro/',include('app.urls',namespace='cadastre')),
	
]

app/urls.py
from django.conf.urls import url, include
from app import views as v

urlpatterns = [

	url(r'^time/lista',v.TeamListView.as_view(),name='list_teams'),
    url(r'^time/atualizar/(?P<pk>\d+)',v.TeamUpdateView.as_view(success_url='../lista'),name='update_team'),
    url(r'^jogador/lista',v.PlayerListView.as_view(),name='list_players'),
    url(r'^jogador/atualizar/(?P<pk>\d+)',v.PlayerUpdateView.as_view(success_url='../lista'),name='update_player'),
    url(r'^quiz/lista',v.QuestionListView.as_view(),name='list_questions'),
    url(r'^quiz/atualizar/(?P<pk>\d+)',v.QuestionUpdateView.as_view(success_url='../lista'),name='update_question'),
    url(r'^quiz/remover/(?P<pk>\d+)',v.DeleteQuestion,name='delete_question'),
    url(r'^quiz/criar/',v.QuestionCreateView.as_view(success_url='../lista'),name='create_question'),
]

templates/airball/cadastre/question/question_form.html
{% extends "airball/template-main.html" %}
{% block header %}
  <title>Cadastro de questão</title>
{% endblock %}
{% block container %}
  <h1>
    {% if not form.instance.pk %}
      Criar questão
    {% else %}
      Atualizar questão
    {% endif %}
  </h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class='btn btn-primary' value="Salvar">

  </form>
{% endblock %}

templates/airball/cadastre/question/question_list.html
{% extends "airball/template-main.html" %}
{% load staticfiles %}
{% block header %} 
  <title>Lista de times</title>
{% endblock %}
{% block container %}
  <h2>Times</h2>
  <button type="button" class="btn btn-primary" style="margin-top:25px;margin-bottom:25px;" data-toggle="modal" data-target="#exampleModal" onclick="document.location = 'criar/'">Novo</button>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Questão</th>
        <th>Excluir</th>
      </tr>
    </thead>
    <tbody>
      {% for question in questions %}
        <tr class='clickable-row' onclick="document.location = 'atualizar/{{question.id}}';">
          <td>{{question.question}}</td>
          <td width="100px">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" onclick="event.stopPropagation();deleteItem({{question.id}});">
              Excluir
            </button>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Confirmação</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Deseja excluir este registro?
        </div>
        <div class="modal-footer">
          <a id="delete-item" href="http://google.com" class='btn btn-primary'>Sim</a>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
        </div>
      </div>
    </div>
  </div>

  <script>
    var base_href = '{% url 'cadastre:delete_question' pk=0 %}';


    function deleteItem(id) {      
      var str = base_href;
      str = str.substring(0,str.lastIndexOf("/"));
      var link = document.getElementById("delete-item");
      link.href = str  + "/" + id;

      $('#myModal').modal('show');
      
    }
    
  </script>

{% endblock %}